export const products = [
    {
        coverimage: './assets/img/phone-cover.jpg',
        name: 'Phone XL',
        price: 799,
        description: "A large phone with one of the best screens",
        heading1: 'sample1',
        heading2: 'sample2',
        heading3: 'sample3',
        headingtext1: 'sampletext1',
        headingtext2: 'sampletext2',
        headingtext3: 'sampletext3',
    },
    {
        coverimage: './assets/img/phone-cover.jpg',
        name: 'Phone L',
        price: 699,
        description: "A middle phone with one of the best screens",
        heading1: 'sample1',
        heading2: 'sample2',
        heading3: 'sample3',
        headingtext1: 'sampletext1',
        headingtext2: 'sampletext2',
        headingtext3: 'sampletext3',
    },
    {
        coverimage: './assets/img/phone-cover.jpg',
        name: 'Phone M',
        price: 599,
        description: "A small phone with one of the best screens",
        heading1: 'sample1',
        heading2: 'sample2',
        heading3: 'sample3',
        headingtext1: 'sampletext1',
        headingtext2: 'sampletext2',
        headingtext3: 'sampletext3',
    },
    {
        coverimage: './assets/img/phone-cover.jpg',
        name: 'Phone S',
        price: 599,
        description: "A special phone with one of the best screens",
        heading1: 'sample1',
        heading2: 'sample2',
        heading3: 'sample3',
        headingtext1: 'sampletext1',
        headingtext2: 'sampletext2',
        headingtext3: 'sampletext3',
    }
];